import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function achievements() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Mert Sancar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
            Achievements and Certification
        </h1>

        <h1 className={styles.description}>
          There are my achievements
        </h1>

        <div className={styles.grid}>
          <a href="https://studentambassadors.microsoft.com/" className={styles.card}>
            <h2>Microsoft Learn Student Ambassador &rarr;</h2>
            <h3>Microsoft</h3>
            <p>Learn Student Ambassadors are a global group of campus leaders who are eager to help students, create tech communities, and develop technical and career skills for the future.</p>
            <p>Aug 2020</p>
          </a>

          <a href="https://ogrencimerkezi.yeditepe.edu.tr/en/individual-and-academic-development" className={styles.card}>
            <h2>Peer Advising Program &rarr;</h2>
            <h3>Individual And Academic Development</h3>
            <p>The mission of the program is to facilitate the adaptation process of our new undergraduate students to university life.</p>
            <p>Sep 2020</p>
          </a>

          <a href="https://uygulamalibilimler.yeditepe.edu.tr/en/software-development" className={styles.card}>
            <h2>Department Representative &rarr;</h2>
            <h3>Yeditepe University</h3>
            <p>Department representative of Software Development department</p>
            <p>2019-2023</p>
          </a>


        </div>

        <h1 className={styles.description}>
        <br></br>
        <br></br>
        </h1>

        <h1 className={styles.description}>
          There are my certifications
        </h1>

        <div className={styles.grid}>

          <a href="https://www.credly.com/badges/61a811b9-d030-4694-a313-8c5ccb30011e?source=linked_in_profile" className={styles.card}>
            <h2>Microsoft Certified: Azure Fundamentals &rarr;</h2>
            <h3>Microsoft</h3>
            <p>April 2021</p>
          </a>

          <a href="https://www.credly.com/badges/dfbb5bfb-a854-4902-80b9-835e869e5575?source=linked_in_profile" className={styles.card}>
            <h2>Microsoft Certified: Azure Data Fundamentals &rarr;</h2>
            <h3>Microsoft</h3>
            <p>May 2021</p>
          </a>

          <a href="https://www.credly.com/badges/c749aa94-c872-40cb-b6c0-4378182c9962?source=linked_in_profile" className={styles.card}>
            <h2>Microsoft Certified: Azure AI Fundamentals &rarr;</h2>
            <h3>Microsoft</h3>
            <p>May 2021</p>
          </a>


        </div>

        <a href="/" className={styles.card}>
            <h2>Back &rarr;</h2>
        </a>

      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Mert Sancar
          </span>
        </a>
      </footer> */}

    </div>
  )
}
