import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Mert Sancar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mert Sancar
        </h1>

        <p className={styles.description}>
          Welcome to my website
        </p>

        <div className={styles.grid}>
          <a href="whoami" className={styles.card}>
            <h2>Who am I ? &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="projects" className={styles.card}>
            <h2>Projects &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="skills"
            className={styles.card}
          >
            <h2>Skills &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="achievements"
            className={styles.card}
          >
            <h2>Achievements & Certifications&rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>

        <div>
        <a href="https://github.com/mertsancar">
            <h2>GitHub &rarr;</h2>
          </a>
          <a href="https://www.linkedin.com/in/mertsancar/">
            <h2>Linkedin &rarr;</h2>
          </a>
        </div>


        </div>
    

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

    </div>
  )
}
