import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function projects() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Mert Sancar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Projects
        </h1>

        <p className={styles.description}>
          There are my projects
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/mertsancar/NeYesek" className={styles.card}>
            <h2>Ne Yesek? &rarr;</h2>
            <p>Ne Yesek? is my first android app with Xamarin. The application asks you for your hunger level as a value between 0 and 5 and then the app selects a random meal from its database based on your hunger status and the app opens a web page where you can order the food.</p>
          </a>

          <a href="https://github.com/mertsancar/CoronaRun" className={styles.card}>
            <h2>CoronaRun &rarr;</h2>
            <p>CoronaRun is my first game with UNITY3D. CoronaRun is a game which we try to run away without getting caught in the coronavirus. While making this game I was inspired by endless running games like Temple Run.</p>
          </a>

          <a href="https://github.com/mertsancar/SumoCars" className={styles.card}>
            <h2>SumoCars &rarr;</h2>
            <p>Sumo Cars is my first multiplayer game with UNITY3D. I'm at the beginning of the Sumo Cars development process, so there are many shortcomings in the game but I will work on it.</p>
          </a>

          <a href="https://github.com/mertsancar/ZIP" className={styles.card}>
            <h2>MertBot &rarr;</h2>
            <p>ZIP is my first gamejam game. I completed this game within 48 hours. The aim of the game is to find the yellow box without room zipped you and move on to the next level. You can go to the link above and test my game.</p>
          </a>

          <a href="https://github.com/7tepe-Dev/QuickOrder" className={styles.card}>
            <h2>Quick Order &rarr;</h2>
            <p>"QuickOrder" is a project I developed with my friends at my university. I took a role in developing the database side of this project.</p>
          </a>

          <a href="https://github.com/mertsancar/Mert-Bot" className={styles.card}>
            <h2>MertBot &rarr;</h2>
            <p>Mert Bot is a discord bot that can help you with many ways</p>
          </a>

          <a href="/" className={styles.card}>
            <h2>Back &rarr;</h2>
        </a>



        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}

    </div>
  )
}
