import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function skills() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Mert Sancar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
            Skills
        </h1>

        <h1 className={styles.description}>
          There are my achievements
        </h1>

        <div className={styles.grid}>

          <a className={styles.card}>
            <h2>C#</h2>
            <p>.NET, Xamarin, Unity3D, Visual Studio</p>
          </a>

          <a className={styles.card}>
            <h2>Python</h2>
            <p>Kivy, Numpy, Selenium, Requests</p>
          </a>

          <a className={styles.card}>
            <h2>Java</h2>
            <p>Object-Oriented Programming</p>
          </a>

          <a className={styles.card}>
            <h2>C++</h2>
            <p>System Analysis and Algorithms</p>
          </a>

          <a className={styles.card}>
            <h2>SQL</h2>
            <p>MySQL, SQL Developer, phpMyAdmin</p>
          </a>

          <a className={styles.card}>
            <h2>HTML / CSS</h2>
            <p>Web Design</p>
          </a>
        </div>


        <div className={styles.grid}>

        <a className={styles.card}>
            <p>GitHub, Desing Patterns, Data Structures, Software Development, Virtual Reality, Project Management, Game Design</p>
          </a>



        </div>

        <a href="/" className={styles.card}>
            <h2>Back &rarr;</h2>
        </a>

      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Mert Sancar
          </span>
        </a>
      </footer> */}

    </div>
  )
}
